# Generated by Django 5.1.4 on 2024-12-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'type', '-is_default'], name='account_add_user_id_8a0fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', '-created_at'], name='account_add_user_id_9ba439_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='account_not_user_id_42f819_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='account_not_user_id_87f092_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user'], name='account_not_user_id_f11d46_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='account_pro_user_id_90d36a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='account_pro_phone_n_14e0d9_idx'),
        ),
    ]
